[2019-01-23T16:08:17.208Z]  @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. Error: ENOENT: no such file or directory, open '../../userdata/data/tnK534JMwwfhvUEycn69HPbhqkt2_teach.csv'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at Object.appendFileSync (fs.js:1258:6)
    at /home/jupyter/commuter/nodejs/pendlaren_node_server.js:229:16
    at /home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:4568:22
    at exceptionGuard (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:691:9)
    at EventList.raise (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9727:17)
    at EventQueue.raiseQueuedEventsMatchingPredicate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9681:41)
    at EventQueue.raiseEventsForChangedPath (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9665:14)
    at Repo.onDataUpdate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:12770:26) 
/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:702
            throw e;
            ^

Error: ENOENT: no such file or directory, open '../../userdata/data/tnK534JMwwfhvUEycn69HPbhqkt2_teach.csv'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at Object.appendFileSync (fs.js:1258:6)
    at /home/jupyter/commuter/nodejs/pendlaren_node_server.js:229:16
    at /home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:4568:22
    at exceptionGuard (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:691:9)
    at EventList.raise (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9727:17)
    at EventQueue.raiseQueuedEventsMatchingPredicate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9681:41)
    at EventQueue.raiseEventsForChangedPath (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9665:14)
    at Repo.onDataUpdate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:12770:26)
[2019-01-23T16:08:17.937Z]  @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. Error: ENOENT: no such file or directory, open '../../userdata/data/tnK534JMwwfhvUEycn69HPbhqkt2_teach.csv'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at Object.appendFileSync (fs.js:1258:6)
    at /home/jupyter/commuter/nodejs/pendlaren_node_server.js:229:16
    at /home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:4568:22
    at exceptionGuard (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:691:9)
    at EventList.raise (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9727:17)
    at EventQueue.raiseQueuedEventsMatchingPredicate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9681:41)
    at EventQueue.raiseEventsForChangedPath (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9665:14)
    at Repo.onDataUpdate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:12770:26) 
/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:702
            throw e;
            ^

Error: ENOENT: no such file or directory, open '../../userdata/data/tnK534JMwwfhvUEycn69HPbhqkt2_teach.csv'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at Object.appendFileSync (fs.js:1258:6)
    at /home/jupyter/commuter/nodejs/pendlaren_node_server.js:229:16
    at /home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:4568:22
    at exceptionGuard (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:691:9)
    at EventList.raise (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9727:17)
    at EventQueue.raiseQueuedEventsMatchingPredicate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9681:41)
    at EventQueue.raiseEventsForChangedPath (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9665:14)
    at Repo.onDataUpdate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:12770:26)
[2019-01-23T17:23:42.531Z]  @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. Error: ENOENT: no such file or directory, open '../../userdata/data/tnK534JMwwfhvUEycn69HPbhqkt2_teach.csv'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at Object.appendFileSync (fs.js:1258:6)
    at /home/jupyter/commuter/nodejs/pendlaren_node_server.js:229:16
    at /home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:4568:22
    at exceptionGuard (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:691:9)
    at EventList.raise (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9727:17)
    at EventQueue.raiseQueuedEventsMatchingPredicate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9681:41)
    at EventQueue.raiseEventsForChangedPath (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9665:14)
    at Repo.onDataUpdate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:12770:26) 
/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:702
            throw e;
            ^

Error: ENOENT: no such file or directory, open '../../userdata/data/tnK534JMwwfhvUEycn69HPbhqkt2_teach.csv'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at Object.appendFileSync (fs.js:1258:6)
    at /home/jupyter/commuter/nodejs/pendlaren_node_server.js:229:16
    at /home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:4568:22
    at exceptionGuard (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:691:9)
    at EventList.raise (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9727:17)
    at EventQueue.raiseQueuedEventsMatchingPredicate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9681:41)
    at EventQueue.raiseEventsForChangedPath (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9665:14)
    at Repo.onDataUpdate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:12770:26)
[2019-01-23T17:24:39.489Z]  @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. Error: ENOENT: no such file or directory, open '../../userdata/data/tnK534JMwwfhvUEycn69HPbhqkt2_teach.csv'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at Object.appendFileSync (fs.js:1258:6)
    at /home/jupyter/commuter/nodejs/pendlaren_node_server.js:229:16
    at /home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:4568:22
    at exceptionGuard (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:691:9)
    at EventList.raise (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9727:17)
    at EventQueue.raiseQueuedEventsMatchingPredicate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9681:41)
    at EventQueue.raiseEventsForChangedPath (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9665:14)
    at Repo.onDataUpdate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:12770:26) 
/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:702
            throw e;
            ^

Error: ENOENT: no such file or directory, open '../../userdata/data/tnK534JMwwfhvUEycn69HPbhqkt2_teach.csv'
    at Object.openSync (fs.js:450:3)
    at Object.writeFileSync (fs.js:1212:35)
    at Object.appendFileSync (fs.js:1258:6)
    at /home/jupyter/commuter/nodejs/pendlaren_node_server.js:229:16
    at /home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:4568:22
    at exceptionGuard (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:691:9)
    at EventList.raise (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9727:17)
    at EventQueue.raiseQueuedEventsMatchingPredicate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9681:41)
    at EventQueue.raiseEventsForChangedPath (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:9665:14)
    at Repo.onDataUpdate_ (/home/jupyter/commuter/nodejs/node_modules/@firebase/database/dist/index.node.cjs.js:12770:26)
